In [100]:
import numpy as np
from scipy.optimize import minimize

In [193]:
x = np.array([[1, 0.1], [0.1, 2]])
y_star = np.linalg.inv(x)
y_sparse= np.diag(np.diag(y_star))
score_sparse = np.trace(y_sparse @ x ) - np.log(np.linalg.det(y_sparse))
print(score_sparse)

2.693172348169138


In [194]:
y_sparse

array([[1.00502513, 0.        ],
       [0.        , 0.50251256]])

In [202]:
def _f(b):
    return (score_sparse - x[0][0] * y_sparse[0][0] - x[1][1] * y_sparse[1][1] - 2 * x[0][1] * b[0] + np.log(np.linalg.det(y_sparse) - b[0] ** 2)) ** 2

In [213]:
b = minimize(_f, [0.5], method="Powell")

/Users/sikai/.pyenv/versions/3.7.6/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


In [214]:
b

   direc: array([[1.]])
     fun: nan
 message: 'NaN result encountered.'
    nfev: 26
     nit: 2
  status: 3
 success: False
       x: array([5.67585792])

In [215]:
y_dense = y_star
y_dense[0][1] = y_dense[1][0] = b.x[0]

In [211]:
y_dense

array([[ 1.00502513e+00, -4.44089210e-16],
       [-4.44089210e-16,  5.02512563e-01]])

In [212]:
score_dense = np.trace(y_dense @ x ) - np.log(np.linalg.det(y_dense))
print(score_dense)

2.693172348169138


In [190]:
y_dense

array([[ 2.08333333, -0.4166875 ],
       [-0.4166875 ,  2.08333333]])